### ISSUE TITLE
Component Not working

### ISSUE THREAD

**Issue by MasterG44** [MLWebTechnologies/PrayerCenter#10]
Hello, Thanks for the component

Please, this is the only Christian prayer component I have found on Joomla! extensions repository. I will beg that you check the component and fix some of the issues that are making this component not to work. I find it a bit difficult to install. Then it installed but it's giving me error. I attach here the screen-shot of the issue.
![prayercenter](https://user-images.githubusercontent.com/31832985/30254491-a60871c4-9691-11e7-978c-fb419a5ed4ad.jpg)

**Comment by DBADIVA** [comment]
Warning
JFile: :read: Unable to open file: /home/sublimel/public_html/logs/com_prayercenter/pcerrorlog.php

**Comment by DBADIVA** [comment]
I cant use the module it wont install with this compnent in the package so that i  can get it to work

**Comment by boluak** [comment]
same problem here: JFile::Read: unable to open pcerrorlog.php

**Comment by boluak** [comment]
after submission of requests, email no longer being sent to moderators, neither is any acknowledgement  displayed or sent to the requester. no errors shown
