### ISSUE TITLE
Deprecated PHP code in version 3.02

### ISSUE THREAD

**Issue by lovetruthact** [MLWebTechnologies/PrayerCenter#13]
Hi There, I just installed this wonderful software, but it is giving me a couple of warning messages I think you will want to attend to soon.

"Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgSystemPrayerCenterEmail has a deprecated constructor in /home/lovetruthact/public_html/stageit/plugins/system/prayercenteremail/prayercenteremail.php on line 10"

and

JFile: :read: Unable to open file: /home/lovetruthact/public_html/stageit/logs/com_prayercenter/pcerrorlog.php

Thanks for the great work you are doing.
May God's Peace bless you and stick to you like a rash on a baby's bottom :-)

Warm regards,
Cor
If you can please update this or tell me how I can correct it that would be great.

**Comment by dteichmer** [comment]
Mike,?
I am still getting this message in 3.0.4.  Has it been resolved or is there a step I can take to resolve it

Thanks!

-Darin
