### ISSUE TITLE
Updated polish translation 

### ISSUE THREAD

**Issue by Piotr2ma** [MLWebTechnologies/PrayerCenter#15]
I have made an update to file with polish translation so it work with PrayerCenter 3.0.3. It is only frontend part and approx 98% complete.
Hope this helps

Piotr
[pl-PL.com_prayercenter.ini.zip](https://github.com/MLWebTechnologies/PrayerCenter/files/1883863/pl-PL.com_prayercenter.ini.zip)

**Comment by MLWebTechnologies** [comment]
Thank you Piotr,  I have published your translation.  God bless!
