### ISSUE TITLE
can not install prayer center 3.0.3

### ISSUE THREAD

**Issue by myale** [MLWebTechnologies/PrayerCenter#16]
Whether i try and upload the main file for install or install from web i get errors.   1 of which if i remember had to do with the .xml file  similar issue was not able to install admin stuff from the temp directory folder...

i really want to add this to my site and appreciate help... i am not a programmer

thanks

**Comment by Piotr2ma** [comment]
Could you provide more information : what is your joomla version ? Which packet do yo try to install ? What exactly error information says ?
Piotr

**Comment by myale** [comment]
Hey there,

 

I have joomla 3.8.7

Just tried again to install prayer center 3.0.3.zip

 

Here is the error I get for uploading the file from my laptop

 

×

Warning

JInstaller: :Install: Can't find Joomla XML setup file.

×

Error

Unable to find install package

 

I don’t know programming  in any way and how php works etc…

 

I really want to have this extention installed fully and used… for my site. 

 

Thanks

Mark

**Comment by Piotr2ma** [comment]
OK, do you downloaded  package from http://mlwebtechnologies.github.io/PrayerCenter/ - if yes the file which you downloaded should be unziped first. Inside this file there is a real zip file with package.  You can also simply dowlnload latest version of the component from github - https://github.com/MLWebTechnologies/PrayerCenter/tree/master/Component/PrayerCenter303 
Let me know if it works.

Piotr

**Comment by myale** [comment]
Hey there again,

 

I downloaded from github  both the unzip first file and then the OTHER File both instances failed to install correctly when I unzipped the unzipfirst file as well as the other…

 

Thanks…

Mark

**Comment by Piotr2ma** [comment]
Ok, so you can do it another way. First on your local computer unzip file com_prayercenter303.zip 
Then copy the whole directory  to directory on webserver (i.e. /var/www/joomla/tmp). Next from joomla admin interface choose to install package from directory - you should enter the complete path - i.e. /var/www/joomla/tmp/com_prayercenter303 .  And give info what is the result
Piotr

**Comment by Piotr2ma** [comment]
Meanwhile I have recalled that during my trials to install prayercenter component I had to modify file prayercenter.xml as it contains reference to non-existing directory. I enclosed "improved" version of this file. Just replace original file (unzip first) and try to install once more.

Piotr
[prayercenter.xml.zip](https://github.com/MLWebTechnologies/PrayerCenter/files/1947071/prayercenter.xml.zip)

**Comment by myale** [comment]
Hey there,

 

I haven’t uploaded anything in ftp in a while…

I never installed anything using the folder install function…

 

Especially with joomla   so I don’t know if I am going to have much luck

 

Mark

**Comment by Piotr2ma** [comment]
Ok, so you can modifiy original zip file. Remove file prayercenter.xml from zip file  and add my version . And give it a try. Or use enclosed modded version. 
Installing this component is not a simple thing nor forcing its admin interface to work but it is possible.

Piotr
[com_prayercenter303_mod.zip](https://github.com/MLWebTechnologies/PrayerCenter/files/1947154/com_prayercenter303_mod.zip)

**Comment by myale** [comment]
Hey there,

 

So aftetr trying to install your modification file  this is what I get….

 

×

Warning

JInstaller: :Install: File does not exist /home/j11rev87sa/mylordsministries.com/tmp/install_5ae088216d665/com_prayercenter303/admin/help

Component Update: Failed to copy administrator files.

×

Error

Error installing component

Top of Form

 

The PrayerCenter Component provides users of a website with the capability to share their prayer concerns with others. Prayer concerns can be posted to the website, sent to members of the the prayer chain, and sent to the Spiritual director or pastor. Users can subscribe to be members of the prayer chain via online form.

 <http://www.mylordsministries.com/administrator/%22http:/www.mlwebtechnologies.com%22> Description: "PrayerCenter"

Support is offered by forum at  <http://www.mylordsministries.com/administrator/%22www.mlwebtechnologies.com%22> www.mlwebtechnologies.com or by email at web@mlwebtechnologies.com

"Hear, O Lord, my righteous plea;
listen to my cry.
Give ear to my prayer-
it does not rise from deceitful lips

I call on you, O God, for you will answer me;
give ear to me and hear my prayer.
Psalm 17:1,6 (NLT)

Bottom of Form

 

I see the prayer center link in the component section of the admin panel…   and this is what I get…

 

From the CPANEL

This is the result

 



An error has occurred.


0 Call to undefined method Joomla\CMS\Log\Logger::addLogger()

 <http://www.mylordsministries.com/administrator>  Return to Control Panel

 

 

Still very stuck….

 

Mark

**Comment by myale** [comment]
Hey there,

 

So that file WORKED… THANKS

 

Now I want to get the modules and install them… please help there  I am so lost to a degree

 

Thanks

Mark

**Comment by myale** [comment]
I spoke a little to soon about the file working…

 

I get the cpanel now… that is working right

 

 

Manage devotionals I get this off the component prayer request list    AND Manage Links  everything else is alright

 

 

 

An error has occurred.

0 [] operator not supported for strings

 <http://www.mylordsministries.com/administrator>  Return to Control Panel

 

 

Thanks for your help so far

Mark

**Comment by MLWebTechnologies** [comment]
I have version 3.0.4 almost done which fixes many things.  I'll take a look into this issue as well.

**Comment by myale** [comment]
Hey again,

 

  so can a list of praer requests be shown on a page that I wish to for my site?  At the same time

 

Mark

**Comment by MLWebTechnologies** [comment]
No, not currently.  That will require new functionality.  I've had similar feature requests before.  So you would like to be able to somehow group requests together and list them on another content page of your site?  Once PrayerCenter is stabilized, I will take a look into this.
