### ISSUE TITLE
Send Request will not work on front end

### ISSUE THREAD

**Issue by bcordis** [MLWebTechnologies/PrayerCenter#7]
Send Request  https://www.nfsda.org/members/prayer-center/newreq.html

Come back with Uncaught SyntaxError: Unexpected token }

**Comment by fbcspringvalley** [comment]
I am able to submit a request with the form but when using the form associated to the link in the menu nothing happens. When I submit with the form I have active in my sidebar there is no response from the site to verify the request. I also can't make it send a notice to the users when a new request is posted.

It appears to be a fantastic addition to our website I hope someone can help me get this corrected.

Thank you

**Comment by MLWebTechnologies** [comment]
I believe this may be an issue with JavaScript.  I am working on an issue with the editor on the new request page not submitting.  The workaround for it is to change the PrayerCenter configuration to not use an editor and use a basic text box.

**Comment by fbcspringvalley** [comment]
Thank you, it is now functional after applying the workaround. Is there a workaround to allow multiple moderators or all administrators confirm requests? I have tried selecting multiple users while selecting moderators or all administrators and and the only time an email is received is while I have moderators and just one user selected to approve.
