### ISSUE TITLE
Error on cpanel page php7

### ISSUE THREAD

**Issue by bcordis** [MLWebTechnologies/PrayerCenter#9]
Call to undefined function eregi() need to replace.

**Comment by GODpleasers** [comment]
What do you mean?

**Comment by bcordis** [comment]
Php7 do not have that function and need to find alternative. Had to stop using the component as it is not ready for php7.

**Comment by GODpleasers** [comment]
> Php7 do not have that function and need to find alternative. Had to stop using the component as it is not ready for php7.

We had alot of issues in php 55 and 56. We kept using it cause we like the component well enough but eventually we totally dropped it cause we kept finding more an d more problems.

**Comment by bcordis** [comment]
I've almost looked at making a new one from the Joomla bible study team. It's a hard one to convert to new coding.

**Comment by GODpleasers** [comment]
> Php7 do not have that function and need to find alternative. Had to stop using the component as it is not ready for php7.

Ya unfortunately the creator of it will not update it. 

> I've almost looked at making a new one from the Joomla bible study team. It's a hard one to convert to new coding.

Please Let us know when you do.

**Comment by bcordis** [comment]
@GODpleasers please see are CWM new project for Prayer Center.  https://www.christianwebministries.org/

**Comment by bcordis** [comment]
Coming soon. Almost all recorded at https://github.com/Joomla-Bible-Study/Prayer
